export const GET_CLAIMS_REQUEST = 'GET_CLAIMS_REQUEST';
export const GET_CLAIMS_SUCCESS = 'GET_CLAIMS_SUCCESS';
export const CREATE_CLAIM_REQUEST = 'CREATE_CLAIM_REQUEST';
export const CREATE_CLAIM_SUCCESS = 'CREATE_CLAIM_SUCCESS';
export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';