export const GET_QUOTES_REQUEST = 'GET_QUOTES_REQUEST';
export const GET_QUOTES_SUCCESS = 'GET_QUOTES_SUCCESS';
export const GET_CART_REQUEST = 'GET_CART_REQUEST';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const ADD_QUOTE_TO_CART_REQUEST = 'ADD_QUOTE_TO_CART_REQUEST';
export const ADD_QUOTE_TO_CART_SUCCESS = 'ADD_QUOTE_TO_CART_SUCCESS';
export const REMOVE_QUOTE_FROM_CART_REQUEST = 'REMOVE_QUOTE_FROM_CART_REQUEST';
export const REMOVE_QUOTE_FROM_CART_SUCCESS = 'REMOVE_QUOTE_FROM_CART_SUCCESS';